<a href="https://colab.research.google.com/github/Bigie11/Swing-calculator-/blob/main/Assignment_Python_for_Data_Science_Using_Nigeria_Datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Answer to assignment

**Part 1**
1. what is data science?
Data science can be defined as the cllection, analysis, organizing and interpretation of data to proffer better solution to you and make better dicisions.

2. Why should a data analyst inspect data before making conclusions?
A data analyst should inspect data first to check for errors, missing values, duplicates, and inconsistencies. This helps ensure the data is accurate and reliable, leading to correct conclusions and better decisions.

3. Why are missing values important in real datasets?
Missing values are important because they can affect the accuracy of data analysis and produce misleading results if ignored. Identifying and handling them properly helps improve the quality and reliability of the analysis.

**Part 2**

In [16]:
import pandas as pd

Marvelous_df = pd.read_csv('/content/drive/MyDrive/nigeria_economic_data.csv')
Marvel_df = pd.read_csv('/content/drive/MyDrive/nigeria_nursing_mothers_healthcare.csv')
Marvey_df = pd.read_csv('/content/drive/MyDrive/nigeria_unemployment_missing_data.csv')

In [5]:
Marvelous_df.head(5)

,Individual_ID,Age,Gender,Region,Location,Education_Level,Occupation,Employment_Type,Monthly_Income_NGN,Poverty_Status
0,8a61ea0b,6,Female,South East,Urban,Primary,Student,Not in Labor Force,0.00,1
1,dda4058f,46,Male,South West,Urban,Primary,Trade/Services,Informal,35516.10,1
2,a77f8728,50,Female,North West,Rural,Primary,Agriculture,Informal,49952.97,1
3,77530bfc,64,Male,South East,Rural,Secondary,Trade/Services,Self-employed,41902.41,1
4,fdbccc7a,4,Male,North East,Rural,NaN,NaN,Not in Labor Force,0.00,1

In [6]:
Marvelous_df.shape

(10000, 10)

In [7]:
Marvelous_df.columns

list(Marvelous_df.columns)

['Individual_ID',
 'Age',
 'Gender',
 'Region',
 'Location',
 'Education_Level',
 'Occupation',
 'Employment_Type',
 'Monthly_Income_NGN',
 'Poverty_Status']

In [9]:
Marvelous_df.dtypes

Individual_ID          object
Age                     int64
Gender                 object
Region                 object
Location               object
Education_Level        object
Occupation             object
Employment_Type        object
Monthly_Income_NGN    float64
Poverty_Status          int64
dtype: object

In [11]:
Marvelous_df.isnull().sum()

Individual_ID            0
Age                      0
Gender                   0
Region                   0
Location                 0
Education_Level       3996
Occupation            1760
Employment_Type          0
Monthly_Income_NGN       0
Poverty_Status           0
dtype: int64

In [13]:
Marvelous_df.describe()

                Age  Monthly_Income_NGN  Poverty_Status
count  10000.000000        1.000000e+04    10000.000000
mean      26.707200        7.750777e+04        0.737300
std       22.019399        1.412193e+05        0.440123
min        0.000000        0.000000e+00        0.000000
25%        8.000000        0.000000e+00        0.000000
50%       20.000000        3.086715e+04        1.000000
75%       44.000000        1.015226e+05        1.000000
max       95.000000        2.341234e+06        1.000000

In [20]:
average_income = Marvelous_df.groupby('Region')['Monthly_Income_NGN'].mean()

print(average_income)

Region
North Central    69751.709115
North East       61911.150794
North West       61959.581737
South East       90900.844619
South South      96329.694739
South West       94405.781358
Name: Monthly_Income_NGN, dtype: float64

In [23]:
Marvel_df.groupby('Geopolitical_Zone')['Residence'].value_counts()

Geopolitical_Zone  Residence
North Central      Rural         773
                   Urban         709
North East         Rural         734
                   Urban         702
North West         Rural        1301
                   Urban        1171
South East         Rural         830
                   Urban         784
South South        Rural         731
                   Urban         725
South West         Rural         817
                   Urban         723
Name: count, dtype: int64

In [24]:
income = Marvey_df.groupby('Education_Level')['Monthly_Income_NGN'].mean()

print(income)

Education_Level
Primary      46918.825968
Secondary    64492.282083
Tertiary     71520.348625
Name: Monthly_Income_NGN, dtype: float64

1. Nigeria economic data.

2. Region, Education Level, Monthly income NGN, Poverty Status.

3. The dataset contains some missing values in a few columns. These missing values should be identified and handled before analysis to avoid inaccurate results.

4. The analysis showed that people came from different locations in different region with difference in their level of education and they were of both gender.

5. Their should be provison of proper education which will lead to better job opportunity and reduce the rate of poverty.